name: cactus
description: "Build AI apps with Cactus"
version: 2.0.0
homepage: https://cactuscompute.com
repository: https://github.com/cactus-compute/cactus-flutter

environment:
  sdk: '>=3.3.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  ffi: ^2.1.4
  dio: ^5.7.0
  dio_smart_retry: ^6.0.0
  path_provider: ^2.1.5
  archive: ^4.0.7
  flat_buffers: ^23.5.26
  path: ^1.9.1
  record: ^6.1.1
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  test: ^1.25.0
  flutter_lints: ^3.0.0
  build_runner: ^2.7.1
  build_version: ^2.1.2

flutter:
  plugin:
    platforms:
      android:
        ffiPlugin: true
      ios:
        ffiPlugin: true
      macos:
        ffiPlugin: true
